/* THIS FILE IS AUTO-GENERATED BY PAYLOAD */
import { AdminPage, generateAdminMetadata } from '@payloadcms/next/views';
import { importMap } from '../importMap'; // You may need to verify this path

export const generateMetadata = ({ params, searchParams }) =>
  generateAdminMetadata({ config: importMap, params, searchParams });

const Page = ({ params, searchParams }) =>
  AdminPage({ config: importMap, params, searchParams });

export default Page;
