/* THIS FILE IS AUTO-GENERATED BY PAYLOAD */
import { RootPage, generatePageMetadata } from '@payloadcms/next/views'
import { importMap } from '../importMap'
import config from '../../../../../payload.config'

type Args = {
  params: Promise<{
    segments: string[]
  }>
  searchParams: Promise<{
    [key: string]: string | string[] | undefined
  }>
}

export const generateMetadata = ({ params, searchParams }: Args) =>
  generatePageMetadata({ config, params, searchParams: searchParams as any })

export default async function Page({ params, searchParams }: Args) {
  return RootPage({
    config,
    importMap,
    params,
    searchParams: searchParams as any,
  })
}